# Generated by Django 5.1.1 on 2024-09-20 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mov_financeira',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 15, 16, 44, 287782), verbose_name='Data'),
        ),
    ]
