# Generated by Django 5.1.1 on 2024-09-24 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0002_mov_financeira_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 19, 42, 1, 567985), verbose_name='Data'),
        ),
    ]
