# Generated by Django 5.1.1 on 2024-09-24 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0003_alter_mov_financeira_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mov_financeira',
            old_name='tipo',
            new_name='aPagar',
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 19, 58, 42, 387020), verbose_name='Data'),
        ),
    ]
