# Generated by Django 5.1.1 on 2024-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0004_rename_tipo_mov_financeira_apagar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100)),
                ('Ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField(max_length=100)),
                ('Ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mov_Financeira',
        ),
    ]
