# Generated by Django 5.1.1 on 2024-09-29 03:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0005_categoria_financeira_categoria_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Login', models.CharField(max_length=45)),
                ('Categoria_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteste.categoria_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mov_Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_pagar', models.BooleanField(default=False)),
                ('Descricao', models.TextField(verbose_name=200)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Data', models.DateTimeField(default=datetime.datetime(2024, 9, 29, 0, 48, 39, 185864), verbose_name='Data')),
                ('Status', models.CharField(max_length=45)),
                ('Meio_de_Transacao', models.CharField(max_length=45)),
                ('Categoria_Financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteste.categoria_financeira')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteste.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
                ('Data_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Data inicio')),
                ('Data_fim_prevista', models.DateField(verbose_name='Data fim prev')),
                ('Data_fim', models.DateField(verbose_name='Data fim')),
                ('Valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ativo', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteste.usuario')),
            ],
        ),
    ]
