# Generated by Django 5.1.1 on 2024-09-29 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0012_alter_categoria_usuario_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 15, 57, 11, 872572), verbose_name='Data'),
        ),
    ]
