# Generated by Django 5.1.1 on 2024-10-02 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0018_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 22, 11, 28, 994341), verbose_name='Data'),
        ),
    ]
