# Generated by Django 5.1.1 on 2024-10-04 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0019_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 20, 10, 55, 848152), verbose_name='Data'),
        ),
    ]
