# Generated by Django 5.1.1 on 2024-10-06 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0020_usuario_ativo_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 10, 35, 49, 858569), verbose_name='Data'),
        ),
    ]
