# Generated by Django 5.1.1 on 2024-10-06 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0021_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 15, 45, 44, 552337), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Senha',
            field=models.CharField(max_length=100),
        ),
    ]
