# Generated by Django 5.1.1 on 2024-10-09 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0022_alter_mov_financeira_data_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 19, 30, 19, 22466), verbose_name='Data'),
        ),
    ]
