# Generated by Django 5.1.1 on 2024-10-13 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0023_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='Cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='Nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 14, 50, 15, 93757), verbose_name='Data'),
        ),
    ]
