# Generated by Django 5.1.1 on 2024-10-13 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0024_empreendimento_cidade_empreendimento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 14, 52, 33, 240630), verbose_name='Data'),
        ),
    ]
