# Generated by Django 5.1.1 on 2024-10-13 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0025_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='UF',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 20, 8, 52, 200002), verbose_name='Data'),
        ),
    ]
