# Generated by Django 5.1.1 on 2024-10-20 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0027_remove_empreendimento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 16, 44, 35, 879239), verbose_name='Data'),
        ),
    ]
