# Generated by Django 5.1.1 on 2024-10-20 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0028_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='Data_inicio',
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_fim',
            field=models.CharField(max_length=10, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_fim_prevista',
            field=models.CharField(max_length=10, verbose_name='Data fim prev'),
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 17, 21, 8, 802987), verbose_name='Data'),
        ),
    ]
