# Generated by Django 5.1.1 on 2024-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0029_remove_empreendimento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.CharField(max_length=10, verbose_name='Data'),
        ),
    ]
