# Generated by Django 5.1.1 on 2024-10-20 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0031_alter_empreendimento_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.datetime(2024, 10, 20, 17, 32, 2, 355668), max_length=10),
        ),
    ]
