# Generated by Django 5.1.1 on 2024-10-20 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0032_empreendimento_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.date(2024, 10, 20), max_length=10),
        ),
    ]
