# Generated by Django 5.1.1 on 2024-10-25 22:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0033_alter_empreendimento_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mov_financeira',
            name='Empreendimento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appteste.empreendimento'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.date(2024, 10, 25), max_length=10),
        ),
    ]
