# Generated by Django 5.1.1 on 2024-10-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0034_mov_financeira_empreendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Descricao',
            field=models.TextField(max_length=200),
        ),
    ]
