# Generated by Django 5.1.1 on 2024-10-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0035_alter_mov_financeira_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mov_financeira',
            name='Status',
        ),
        migrations.AddField(
            model_name='mov_financeira',
            name='Pendente',
            field=models.BooleanField(default=False),
        ),
    ]
