# Generated by Django 5.1.1 on 2024-10-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0037_remove_mov_financeira_meio_de_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhaTabelaExistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'minha_tabela_existente',
            },
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.date(2024, 10, 26), max_length=10),
        ),
    ]
