# Generated by Django 5.1.1 on 2024-10-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0038_minhatabelaexistente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minhatabelaexistente',
            options={'managed': False},
        ),
    ]
