# Generated by Django 5.1.1 on 2024-10-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0039_alter_minhatabelaexistente_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinhaTabelaExistente',
        ),
    ]
