# Generated by Django 5.1.1 on 2024-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0040_delete_minhatabelaexistente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mov_financeira',
            name='Empreendimento',
        ),
        migrations.AddField(
            model_name='mov_financeira',
            name='Empreendimento_id',
            field=models.IntegerField(default=2),
        ),
    ]
