# Generated by Django 5.1.1 on 2024-10-29 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0041_remove_mov_financeira_empreendimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mov_financeira',
            name='Usuario_id',
        ),
        migrations.AddField(
            model_name='mov_financeira',
            name='Usuario',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.date(2024, 10, 29), max_length=10),
        ),
    ]
