# Generated by Django 5.1.1 on 2024-10-31 11:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0042_remove_mov_financeira_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.CharField(default=datetime.date(2024, 10, 31), max_length=10),
        ),
        migrations.AlterField(
            model_name='mov_financeira',
            name='Empreendimento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteste.empreendimento'),
        ),
    ]
