# Generated by Django 5.1.1 on 2024-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0043_alter_empreendimento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Empreendimento_id',
            field=models.IntegerField(default=2),
        ),
    ]
