# Generated by Django 5.1.1 on 2024-10-31 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0045_alter_mov_financeira_empreendimento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_financeira',
            name='Data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
