# Generated by Django 5.1.1 on 2024-11-02 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0046_alter_mov_financeira_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_financeira',
            name='Nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_fim',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_fim_prevista',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='Data_inicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
